// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package csr_pkg;

    localparam CSR_DATA_WIDTH = 32;
    localparam CSR_MIN_ADDR_WIDTH = 10;

    typedef struct {
        logic [31:0] next;
        logic we;
    } csr__ip_lookup_engine__table_allowed_ip_f0fa63ea_endpoint_c8786fe9_public_key_0110000d__endpoint_wbuffer_trigger_b607a200__address__in_t;

    typedef struct {
        logic [15:0] next;
        logic we;
    } csr__ip_lookup_engine__table_allowed_ip_f0fa63ea_endpoint_c8786fe9_public_key_0110000d__endpoint_wbuffer_trigger_b607a200__port__in_t;

    typedef struct {
        logic [2:0] next;
        logic we;
    } csr__ip_lookup_engine__table_allowed_ip_f0fa63ea_endpoint_c8786fe9_public_key_0110000d__endpoint_wbuffer_trigger_b607a200__interface__in_t;

    typedef struct {
        csr__ip_lookup_engine__table_allowed_ip_f0fa63ea_endpoint_c8786fe9_public_key_0110000d__endpoint_wbuffer_trigger_b607a200__address__in_t address;
        csr__ip_lookup_engine__table_allowed_ip_f0fa63ea_endpoint_c8786fe9_public_key_0110000d__endpoint_wbuffer_trigger_b607a200__port__in_t port;
        csr__ip_lookup_engine__table_allowed_ip_f0fa63ea_endpoint_c8786fe9_public_key_0110000d__endpoint_wbuffer_trigger_b607a200__interface__in_t interface_;
    } csr__ip_lookup_engine__table_allowed_ip_f0fa63ea_endpoint_c8786fe9_public_key_0110000d__endpoint_wbuffer_trigger_b607a200__in_t;

    typedef struct {
        csr__ip_lookup_engine__table_allowed_ip_f0fa63ea_endpoint_c8786fe9_public_key_0110000d__endpoint_wbuffer_trigger_b607a200__in_t endpoint;
    } csr__ip_lookup_engine__table_allowed_ip_f0fa63ea_endpoint_c8786fe9_public_key_0110000d__in_t;

    typedef struct {
        csr__ip_lookup_engine__table_allowed_ip_f0fa63ea_endpoint_c8786fe9_public_key_0110000d__in_t table_[16];
    } csr__ip_lookup_engine__in_t;

    typedef struct {
        csr__ip_lookup_engine__in_t ip_lookup_engine;
    } csr__in_t;

    typedef struct {
        logic [31:0] value;
    } csr__ip_lookup_engine__table_allowed_ip_f0fa63ea_endpoint_c8786fe9_public_key_0110000d__ip_address_wbuffer_trigger_b607a200__address__out_t;

    typedef struct {
        logic [31:0] value;
    } csr__ip_lookup_engine__table_allowed_ip_f0fa63ea_endpoint_c8786fe9_public_key_0110000d__ip_address_wbuffer_trigger_b607a200__mask__out_t;

    typedef struct {
        csr__ip_lookup_engine__table_allowed_ip_f0fa63ea_endpoint_c8786fe9_public_key_0110000d__ip_address_wbuffer_trigger_b607a200__address__out_t address;
        csr__ip_lookup_engine__table_allowed_ip_f0fa63ea_endpoint_c8786fe9_public_key_0110000d__ip_address_wbuffer_trigger_b607a200__mask__out_t mask;
    } csr__ip_lookup_engine__table_allowed_ip_f0fa63ea_endpoint_c8786fe9_public_key_0110000d__ip_address_wbuffer_trigger_b607a200__out_t;

    typedef struct {
        logic [31:0] value;
    } csr__ip_lookup_engine__table_allowed_ip_f0fa63ea_endpoint_c8786fe9_public_key_0110000d__public_key_wbuffer_trigger_b607a200__key__out_t;

    typedef struct {
        csr__ip_lookup_engine__table_allowed_ip_f0fa63ea_endpoint_c8786fe9_public_key_0110000d__public_key_wbuffer_trigger_b607a200__key__out_t key;
    } csr__ip_lookup_engine__table_allowed_ip_f0fa63ea_endpoint_c8786fe9_public_key_0110000d__public_key_wbuffer_trigger_b607a200__out_t;

    typedef struct {
        logic [31:0] value;
    } csr__ip_lookup_engine__table_allowed_ip_f0fa63ea_endpoint_c8786fe9_public_key_0110000d__endpoint_wbuffer_trigger_b607a200__address__out_t;

    typedef struct {
        logic [15:0] value;
    } csr__ip_lookup_engine__table_allowed_ip_f0fa63ea_endpoint_c8786fe9_public_key_0110000d__endpoint_wbuffer_trigger_b607a200__port__out_t;

    typedef struct {
        logic [2:0] value;
    } csr__ip_lookup_engine__table_allowed_ip_f0fa63ea_endpoint_c8786fe9_public_key_0110000d__endpoint_wbuffer_trigger_b607a200__interface__out_t;

    typedef struct {
        csr__ip_lookup_engine__table_allowed_ip_f0fa63ea_endpoint_c8786fe9_public_key_0110000d__endpoint_wbuffer_trigger_b607a200__address__out_t address;
        csr__ip_lookup_engine__table_allowed_ip_f0fa63ea_endpoint_c8786fe9_public_key_0110000d__endpoint_wbuffer_trigger_b607a200__port__out_t port;
        csr__ip_lookup_engine__table_allowed_ip_f0fa63ea_endpoint_c8786fe9_public_key_0110000d__endpoint_wbuffer_trigger_b607a200__interface__out_t interface_;
    } csr__ip_lookup_engine__table_allowed_ip_f0fa63ea_endpoint_c8786fe9_public_key_0110000d__endpoint_wbuffer_trigger_b607a200__out_t;

    typedef struct {
        csr__ip_lookup_engine__table_allowed_ip_f0fa63ea_endpoint_c8786fe9_public_key_0110000d__ip_address_wbuffer_trigger_b607a200__out_t allowed_ip[2];
        csr__ip_lookup_engine__table_allowed_ip_f0fa63ea_endpoint_c8786fe9_public_key_0110000d__public_key_wbuffer_trigger_b607a200__out_t public_key;
        csr__ip_lookup_engine__table_allowed_ip_f0fa63ea_endpoint_c8786fe9_public_key_0110000d__endpoint_wbuffer_trigger_b607a200__out_t endpoint;
    } csr__ip_lookup_engine__table_allowed_ip_f0fa63ea_endpoint_c8786fe9_public_key_0110000d__out_t;

    typedef struct {
        logic value;
    } csr__ip_lookup_engine__control__update__out_t;

    typedef struct {
        csr__ip_lookup_engine__control__update__out_t update;
    } csr__ip_lookup_engine__control__out_t;

    typedef struct {
        csr__ip_lookup_engine__table_allowed_ip_f0fa63ea_endpoint_c8786fe9_public_key_0110000d__out_t table_[16];
        csr__ip_lookup_engine__control__out_t control;
    } csr__ip_lookup_engine__out_t;

    typedef struct {
        csr__ip_lookup_engine__out_t ip_lookup_engine;
    } csr__out_t;
endpackage
