# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a100tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/ax/AX7103_2019_1/check_demo/check_demo.cache/wt [current_project]
set_property parent.project_path D:/ax/AX7103_2019_1/check_demo/check_demo.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/ax/AX7103_2019_1/check_demo/check_demo.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/mac/arp_cache.v
  D:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/mac/rx/arp_rx.v
  D:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/mac/tx/arp_tx.v
  D:/ax/AX7103_2019_1/check_demo/src/sd/sources_1/src/ax_debounce.v
  D:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/mac/crc.v
  D:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/new/ethernet_2port.v
  D:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/imports/src/ethernet_test.v
  D:/ax/AX7103_2019_1/check_demo/src/eth/arbi/gmii_arbi.v
  D:/ax/AX7103_2019_1/check_demo/src/eth/arbi/gmii_rx_buffer.v
  D:/ax/AX7103_2019_1/check_demo/src/eth/arbi/gmii_tx_buffer.v
  D:/ax/AX7103_2019_1/check_demo/src/hdmi/sources_1/imports/src/hdmi_loop.v
  D:/ax/AX7103_2019_1/check_demo/src/hdmi/sources_1/imports/src/i2c_master/i2c_config.v
  D:/ax/AX7103_2019_1/check_demo/src/hdmi/sources_1/imports/src/i2c_master/timescale.v
  D:/ax/AX7103_2019_1/check_demo/src/hdmi/sources_1/imports/src/i2c_master/i2c_master_defines.v
  D:/ax/AX7103_2019_1/check_demo/src/hdmi/sources_1/imports/src/i2c_master/i2c_master_bit_ctrl.v
  D:/ax/AX7103_2019_1/check_demo/src/hdmi/sources_1/imports/src/i2c_master/i2c_master_byte_ctrl.v
  D:/ax/AX7103_2019_1/check_demo/src/hdmi/sources_1/imports/src/i2c_master/i2c_master_top.v
  D:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/mac/icmp_reply.v
  D:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/mac/rx/ip_rx.v
  D:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/mac/tx/ip_tx.v
  D:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/mac/tx/ip_tx_mode.v
  D:/ax/AX7103_2019_1/check_demo/src/key/src/key_test.v
  D:/ax/AX7103_2019_1/check_demo/src/hdmi/sources_1/lut_hdmi.v
  D:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/mac/rx/mac_rx1.v
  D:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/mac/rx/mac_rx_top.v
  D:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/mac/mac_test.v
  D:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/mac/mac_top.v
  D:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/mac/tx/mac_tx.v
  D:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/mac/tx/mac_tx_mode.v
  D:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/mac/tx/mac_tx_top.v
  D:/ax/AX7103_2019_1/check_demo/src/ddr/ddr3_test.srcs/sources_1/usr_src/mem_burst.v
  D:/ax/AX7103_2019_1/check_demo/src/ddr/ddr3_test.srcs/sources_1/usr_src/mem_test.v
  D:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/new/reset.v
  D:/ax/AX7103_2019_1/check_demo/src/sd/sources_1/src/sd_card/sd_card_cmd.v
  D:/ax/AX7103_2019_1/check_demo/src/sd/sources_1/src/sd_card/sd_card_sec_read_write.v
  D:/ax/AX7103_2019_1/check_demo/src/sd/sources_1/src/sd_card_test.v
  D:/ax/AX7103_2019_1/check_demo/src/sd/sources_1/src/sd_card/sd_card_top.v
  D:/ax/AX7103_2019_1/check_demo/src/eth/mdio/smi_config.v
  D:/ax/AX7103_2019_1/check_demo/src/eth/mdio/smi_read_write.v
  D:/ax/AX7103_2019_1/check_demo/src/sd/sources_1/src/sd_card/spi_master.v
  D:/ax/AX7103_2019_1/check_demo/src/ddr/ddr3_test.srcs/sources_1/usr_src/top.v
  D:/ax/AX7103_2019_1/check_demo/src/uart/sources_1/src/uart_rx.v
  D:/ax/AX7103_2019_1/check_demo/src/uart/sources_1/src/uart_test.v
  D:/ax/AX7103_2019_1/check_demo/src/uart/sources_1/src/uart_tx.v
  D:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/mac/rx/udp_rx.v
  D:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/mac/tx/udp_tx.v
  D:/ax/AX7103_2019_1/check_demo/src/eth/util_gmii_to_rgmii.v
  D:/ax/AX7103_2019_1/check_demo/check_demo.srcs/sources_1/new/check_demo.v
}
read_ip -quiet D:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/ip/icmp_rx_ram_8_256/icmp_rx_ram_8_256.xci
set_property used_in_implementation false [get_files -all d:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/ip/icmp_rx_ram_8_256/icmp_rx_ram_8_256_ooc.xdc]

read_ip -quiet D:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/ip/udp_rx_ram_8_2048/udp_rx_ram_8_2048.xci
set_property used_in_implementation false [get_files -all d:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/ip/udp_rx_ram_8_2048/udp_rx_ram_8_2048_ooc.xdc]

read_ip -quiet D:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/ip/udp_checksum_fifo/udp_checksum_fifo.xci
set_property used_in_implementation false [get_files -all d:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/ip/udp_checksum_fifo/udp_checksum_fifo.xdc]
set_property used_in_implementation false [get_files -all d:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/ip/udp_checksum_fifo/udp_checksum_fifo_ooc.xdc]

read_ip -quiet D:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/ip/udp_tx_data_fifo/udp_tx_data_fifo.xci
set_property used_in_implementation false [get_files -all d:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/ip/udp_tx_data_fifo/udp_tx_data_fifo.xdc]
set_property used_in_implementation false [get_files -all d:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/ip/udp_tx_data_fifo/udp_tx_data_fifo_ooc.xdc]

read_ip -quiet D:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/ip/len_fifo/len_fifo.xci
set_property used_in_implementation false [get_files -all d:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/ip/len_fifo/len_fifo.xdc]
set_property used_in_implementation false [get_files -all d:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/ip/len_fifo/len_fifo_ooc.xdc]

read_ip -quiet D:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/ip/eth_data_fifo/eth_data_fifo.xci
set_property used_in_implementation false [get_files -all d:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/ip/eth_data_fifo/eth_data_fifo.xdc]
set_property used_in_implementation false [get_files -all d:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/ip/eth_data_fifo/eth_data_fifo_ooc.xdc]

read_ip -quiet D:/ax/AX7103_2019_1/check_demo/src/ddr/ddr3_test.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all d:/ax/AX7103_2019_1/check_demo/src/ddr/ddr3_test.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/ax/AX7103_2019_1/check_demo/src/ddr/ddr3_test.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/ax/AX7103_2019_1/check_demo/src/ddr/ddr3_test.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/ax/AX7103_2019_1/check_demo/src/ddr/ddr3_test.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc]

read_ip -quiet D:/ax/AX7103_2019_1/check_demo/src/ddr/ddr3_test.srcs/sources_1/ip/ddr3/ddr3.xci
set_property used_in_implementation false [get_files -all d:/ax/AX7103_2019_1/check_demo/src/ddr/ddr3_test.srcs/sources_1/ip/ddr3/ddr3/user_design/constraints/ddr3.xdc]
set_property used_in_implementation false [get_files -all d:/ax/AX7103_2019_1/check_demo/src/ddr/ddr3_test.srcs/sources_1/ip/ddr3/ddr3/user_design/constraints/ddr3_ooc.xdc]

read_ip -quiet d:/ax/AX7103_2019_1/check_demo/check_demo.srcs/sources_1/ip/ila_1/ila_1.xci
set_property used_in_synthesis false [get_files -all d:/ax/AX7103_2019_1/check_demo/check_demo.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/ax/AX7103_2019_1/check_demo/check_demo.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/ax/AX7103_2019_1/check_demo/check_demo.srcs/sources_1/ip/ila_1/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/ax/AX7103_2019_1/check_demo/check_demo.srcs/sources_1/ip/ila_1/ila_1_ooc.xdc]

read_ip -quiet d:/ax/AX7103_2019_1/check_demo/check_demo.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/ax/AX7103_2019_1/check_demo/check_demo.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/ax/AX7103_2019_1/check_demo/check_demo.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/ax/AX7103_2019_1/check_demo/check_demo.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/ax/AX7103_2019_1/check_demo/src/sd/constrs_1/new/sd_card_test.xdc
set_property used_in_implementation false [get_files D:/ax/AX7103_2019_1/check_demo/src/sd/constrs_1/new/sd_card_test.xdc]

read_xdc D:/ax/AX7103_2019_1/check_demo/src/key/constrs_1/new/key.xdc
set_property used_in_implementation false [get_files D:/ax/AX7103_2019_1/check_demo/src/key/constrs_1/new/key.xdc]

read_xdc D:/ax/AX7103_2019_1/check_demo/src/eth/constrs_1/new/top.xdc
set_property used_in_implementation false [get_files D:/ax/AX7103_2019_1/check_demo/src/eth/constrs_1/new/top.xdc]

read_xdc D:/ax/AX7103_2019_1/check_demo/src/hdmi/constrs_1/new/hdmi_loop.xdc
set_property used_in_implementation false [get_files D:/ax/AX7103_2019_1/check_demo/src/hdmi/constrs_1/new/hdmi_loop.xdc]

read_xdc D:/ax/AX7103_2019_1/check_demo/src/uart/constrs_1/new/uart_test.xdc
set_property used_in_implementation false [get_files D:/ax/AX7103_2019_1/check_demo/src/uart/constrs_1/new/uart_test.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top check_demo -part xc7a100tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef check_demo.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file check_demo_utilization_synth.rpt -pb check_demo_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
