# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/ax/AX7103_2019_1/check_demo/src/sd/constrs_1/new/sd_card_test.xdc

# XDC: D:/ax/AX7103_2019_1/check_demo/src/key/constrs_1/new/key.xdc

# XDC: D:/ax/AX7103_2019_1/check_demo/src/eth/constrs_1/new/top.xdc

# XDC: D:/ax/AX7103_2019_1/check_demo/src/hdmi/constrs_1/new/hdmi_loop.xdc

# XDC: D:/ax/AX7103_2019_1/check_demo/src/uart/constrs_1/new/uart_test.xdc

# IP: D:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/ip/icmp_rx_ram_8_256/icmp_rx_ram_8_256.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==icmp_rx_ram_8_256 || ORIG_REF_NAME==icmp_rx_ram_8_256} -quiet] -quiet

# IP: D:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/ip/udp_rx_ram_8_2048/udp_rx_ram_8_2048.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==udp_rx_ram_8_2048 || ORIG_REF_NAME==udp_rx_ram_8_2048} -quiet] -quiet

# IP: D:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/ip/udp_checksum_fifo/udp_checksum_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==udp_checksum_fifo || ORIG_REF_NAME==udp_checksum_fifo} -quiet] -quiet

# IP: D:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/ip/udp_tx_data_fifo/udp_tx_data_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==udp_tx_data_fifo || ORIG_REF_NAME==udp_tx_data_fifo} -quiet] -quiet

# IP: D:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/ip/len_fifo/len_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==len_fifo || ORIG_REF_NAME==len_fifo} -quiet] -quiet

# IP: D:/ax/AX7103_2019_1/check_demo/src/eth/sources_1/ip/eth_data_fifo/eth_data_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==eth_data_fifo || ORIG_REF_NAME==eth_data_fifo} -quiet] -quiet

# IP: D:/ax/AX7103_2019_1/check_demo/src/ddr/ddr3_test.srcs/sources_1/ip/ila_0/ila_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# IP: D:/ax/AX7103_2019_1/check_demo/src/ddr/ddr3_test.srcs/sources_1/ip/ddr3/ddr3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr3 || ORIG_REF_NAME==ddr3} -quiet] -quiet
