# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.cache/wt [current_project]
set_property parent.project_path G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo g:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/i2c_master/timescale.v
  G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/i2c_master/i2c_master_defines.v
}
set_property file_type "Verilog Header" [get_files G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/i2c_master/timescale.v]
set_property file_type "Verilog Header" [get_files G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/i2c_master/i2c_master_defines.v]
read_verilog -library xil_defaultlib {
  G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/mac/arp_cache.v
  G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/mac/rx/arp_rx.v
  G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/mac/tx/arp_tx.v
  G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/new/camera_delay.v
  G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/new/cmos_select.v
  G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/mac/crc.v
  G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/mac/dpram.v
  G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/imports/src/ethernet_test.v
  G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/i2c_master/i2c_config.v
  G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/i2c_master/i2c_master_bit_ctrl.v
  G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/i2c_master/i2c_master_byte_ctrl.v
  G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/i2c_master/i2c_master_top.v
  G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/mac/icmp_reply.v
  G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/mac/rx/ip_rx.v
  G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/mac/tx/ip_tx.v
  G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/mac/tx/ip_tx_mode.v
  G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/new/lut_ov5640_rgb565_800_600.v
  G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/mac/rx/mac_rx.v
  G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/mac/rx/mac_rx_top.v
  G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/mac/mac_test.v
  G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/mac/mac_top.v
  G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/mac/tx/mac_tx.v
  G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/mac/tx/mac_tx_mode.v
  G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/mac/tx/mac_tx_top.v
  G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/new/reset.v
  G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/mdio/smi_config.v
  G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/mdio/smi_read_write.v
  G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/mac/rx/udp_rx.v
  G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/mac/tx/udp_tx.v
  G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/imports/src/util_gmii_to_rgmii.v
  G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/new/ethernet_2port.v
}
read_ip -quiet G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/ip/camera_fifo/camera_fifo.xci
set_property used_in_implementation false [get_files -all g:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/ip/camera_fifo/camera_fifo.xdc]
set_property used_in_implementation false [get_files -all g:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/ip/camera_fifo/camera_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all g:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/sources_1/ip/camera_fifo/camera_fifo_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/constrs_1/new/top.xdc
set_property used_in_implementation false [get_files G:/ax7103b/vivado/video_ethernet/video_ethernet/eth_test.srcs/constrs_1/new/top.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top ethernet_2port -part xc7a100tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ethernet_2port.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ethernet_2port_utilization_synth.rpt -pb ethernet_2port_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
