# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/demo_AX7050/demo_ax7050/19_ethernet_1g_100M/rgmii_ethernet/.Xil/Vivado-3396-ALINX000008-PC/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7s50fgga484-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include d:/demo_AX7050/demo_ax7050/19_ethernet_1g_100M/rgmii_ethernet/eth_test.srcs/sources_1/ip/rxd_clk {
      C:/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      C:/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include d:/demo_AX7050/demo_ax7050/19_ethernet_1g_100M/rgmii_ethernet/eth_test.srcs/sources_1/ip/rxd_clk {
      D:/demo_AX7050/demo_ax7050/19_ethernet_1g_100M/rgmii_ethernet/.Xil/Vivado-3396-ALINX000008-PC/realtime/blk_mem_gen_0_stub.v
      D:/demo_AX7050/demo_ax7050/19_ethernet_1g_100M/rgmii_ethernet/.Xil/Vivado-3396-ALINX000008-PC/realtime/rxd_clk_stub.v
      D:/demo_AX7050/demo_ax7050/19_ethernet_1g_100M/rgmii_ethernet/eth_test.srcs/sources_1/imports/rtl/crc.v
      D:/demo_AX7050/demo_ax7050/19_ethernet_1g_100M/rgmii_ethernet/eth_test.srcs/sources_1/imports/rtl/iprecieve.v
      D:/demo_AX7050/demo_ax7050/19_ethernet_1g_100M/rgmii_ethernet/eth_test.srcs/sources_1/imports/rtl/ipsend.v
      D:/demo_AX7050/demo_ax7050/19_ethernet_1g_100M/rgmii_ethernet/eth_test.srcs/sources_1/imports/src/reset.v
      D:/demo_AX7050/demo_ax7050/19_ethernet_1g_100M/rgmii_ethernet/eth_test.srcs/sources_1/imports/rtl/udp.v
      D:/demo_AX7050/demo_ax7050/19_ethernet_1g_100M/rgmii_ethernet/eth_test.srcs/sources_1/imports/src/util_gmii_to_rgmii.v
      D:/demo_AX7050/demo_ax7050/19_ethernet_1g_100M/rgmii_ethernet/eth_test.srcs/sources_1/imports/src/ethernet_test.v
    }
      rt::read_vhdl -lib xil_defaultlib {
      D:/demo_AX7050/demo_ax7050/19_ethernet_1g_100M/rgmii_ethernet/eth_test.srcs/sources_1/imports/miim/miim_types.vhd
      D:/demo_AX7050/demo_ax7050/19_ethernet_1g_100M/rgmii_ethernet/eth_test.srcs/sources_1/imports/miim/utility.vhd
      D:/demo_AX7050/demo_ax7050/19_ethernet_1g_100M/rgmii_ethernet/eth_test.srcs/sources_1/imports/miim/miim.vhd
      D:/demo_AX7050/demo_ax7050/19_ethernet_1g_100M/rgmii_ethernet/eth_test.srcs/sources_1/imports/miim/miim_registers.vhd
      D:/demo_AX7050/demo_ax7050/19_ethernet_1g_100M/rgmii_ethernet/eth_test.srcs/sources_1/imports/miim/miim_control.vhd
      D:/demo_AX7050/demo_ax7050/19_ethernet_1g_100M/rgmii_ethernet/eth_test.srcs/sources_1/imports/miim/miim_top.vhd
    }
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top ethernet_test
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "D:/demo_AX7050/demo_ax7050/19_ethernet_1g_100M/rgmii_ethernet/.Xil/Vivado-3396-ALINX000008-PC/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
