# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/ax7103b/vivado/ethernet_test/eth_test.srcs/sources_1/ip/len_fifo/len_fifo.xci
# IP: The module: 'len_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/ax7103b/vivado/ethernet_test/eth_test.srcs/sources_1/ip/len_fifo/len_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'len_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: g:/ax7103b/vivado/ethernet_test/eth_test.srcs/sources_1/ip/len_fifo/len_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'len_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: G:/ax7103b/vivado/ethernet_test/eth_test.srcs/sources_1/ip/len_fifo/len_fifo.xci
# IP: The module: 'len_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/ax7103b/vivado/ethernet_test/eth_test.srcs/sources_1/ip/len_fifo/len_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'len_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: g:/ax7103b/vivado/ethernet_test/eth_test.srcs/sources_1/ip/len_fifo/len_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'len_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
