
####################hdmi_out hdmi_in###################
set_property PACKAGE_PIN M13 [get_ports vout_clk]
set_property PACKAGE_PIN V14 [get_ports {vout_data[0]}]
set_property PACKAGE_PIN H14 [get_ports {vout_data[1]}]
set_property PACKAGE_PIN J14 [get_ports {vout_data[2]}]
set_property PACKAGE_PIN K13 [get_ports {vout_data[3]}]
set_property PACKAGE_PIN K14 [get_ports {vout_data[4]}]
set_property PACKAGE_PIN L13 [get_ports {vout_data[5]}]
set_property PACKAGE_PIN L19 [get_ports {vout_data[6]}]
set_property PACKAGE_PIN L20 [get_ports {vout_data[7]}]
set_property PACKAGE_PIN K17 [get_ports {vout_data[8]}]
set_property PACKAGE_PIN J17 [get_ports {vout_data[9]}]
set_property PACKAGE_PIN L16 [get_ports {vout_data[10]}]
set_property PACKAGE_PIN K16 [get_ports {vout_data[11]}]
set_property PACKAGE_PIN L14 [get_ports {vout_data[12]}]
set_property PACKAGE_PIN L15 [get_ports {vout_data[13]}]
set_property PACKAGE_PIN M15 [get_ports {vout_data[14]}]
set_property PACKAGE_PIN M16 [get_ports {vout_data[15]}]
set_property PACKAGE_PIN L18 [get_ports {vout_data[16]}]
set_property PACKAGE_PIN M18 [get_ports {vout_data[17]}]
set_property PACKAGE_PIN N18 [get_ports {vout_data[18]}]
set_property PACKAGE_PIN N19 [get_ports {vout_data[19]}]
set_property PACKAGE_PIN M20 [get_ports {vout_data[20]}]
set_property PACKAGE_PIN N20 [get_ports {vout_data[21]}]
set_property PACKAGE_PIN L21 [get_ports {vout_data[22]}]
set_property PACKAGE_PIN M21 [get_ports {vout_data[23]}]
set_property PACKAGE_PIN V13 [get_ports vout_de]
set_property PACKAGE_PIN T15 [get_ports vout_hs]
set_property PACKAGE_PIN J19 [get_ports hdmi_nreset]
set_property PACKAGE_PIN T14 [get_ports vout_vs]
set_property PACKAGE_PIN E16 [get_ports hdmi_scl]
set_property PACKAGE_PIN F16 [get_ports hdmi_sda]

set_property IOSTANDARD LVCMOS33 [get_ports vout_clk]
set_property IOSTANDARD LVCMOS33 [get_ports {vout_data[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports vout_de]
set_property IOSTANDARD LVCMOS33 [get_ports vout_hs]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_nreset]
set_property IOSTANDARD LVCMOS33 [get_ports vout_vs]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_scl]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_sda]

set_property SLEW FAST [get_ports {vout_data[*]}]
set_property SLEW FAST [get_ports vout_de]
set_property SLEW FAST [get_ports vout_hs]
set_property SLEW FAST [get_ports vout_vs]

set_property PACKAGE_PIN K21 [get_ports vin_clk]
set_property PACKAGE_PIN H18 [get_ports {vin_data[0]}]
set_property PACKAGE_PIN N22 [get_ports {vin_data[1]}]
set_property PACKAGE_PIN M22 [get_ports {vin_data[2]}]
set_property PACKAGE_PIN K22 [get_ports {vin_data[3]}]
set_property PACKAGE_PIN J22 [get_ports {vin_data[4]}]
set_property PACKAGE_PIN H22 [get_ports {vin_data[5]}]
set_property PACKAGE_PIN H20 [get_ports {vin_data[6]}]
set_property PACKAGE_PIN G20 [get_ports {vin_data[7]}]
set_property PACKAGE_PIN G22 [get_ports {vin_data[8]}]
set_property PACKAGE_PIN G21 [get_ports {vin_data[9]}]
set_property PACKAGE_PIN D22 [get_ports {vin_data[10]}]
set_property PACKAGE_PIN E22 [get_ports {vin_data[11]}]
set_property PACKAGE_PIN D21 [get_ports {vin_data[12]}]
set_property PACKAGE_PIN E21 [get_ports {vin_data[13]}]
set_property PACKAGE_PIN B21 [get_ports {vin_data[14]}]
set_property PACKAGE_PIN A21 [get_ports {vin_data[15]}]
set_property PACKAGE_PIN F21 [get_ports {vin_data[16]}]
set_property PACKAGE_PIN M17 [get_ports {vin_data[17]}]
set_property PACKAGE_PIN J16 [get_ports {vin_data[18]}]
set_property PACKAGE_PIN F15 [get_ports {vin_data[19]}]
set_property PACKAGE_PIN G17 [get_ports {vin_data[20]}]
set_property PACKAGE_PIN G18 [get_ports {vin_data[21]}]
set_property PACKAGE_PIN G15 [get_ports {vin_data[22]}]
set_property PACKAGE_PIN G16 [get_ports {vin_data[23]}]
set_property PACKAGE_PIN H17 [get_ports vin_de]
set_property PACKAGE_PIN K19 [get_ports vin_hs]
set_property PACKAGE_PIN H19 [get_ports hdmi_in_nreset]
set_property PACKAGE_PIN K18 [get_ports vin_vs]

set_property IOSTANDARD LVCMOS33 [get_ports vin_clk]
set_property IOSTANDARD LVCMOS33 [get_ports {vin_data[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports vin_de]
set_property IOSTANDARD LVCMOS33 [get_ports vin_hs]
set_property IOSTANDARD LVCMOS33 [get_ports vin_vs]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_in_nreset]


set_property DRIVE 12 [get_ports {vout_data[12]}]
set_property DRIVE 16 [get_ports vout_clk]
set_property DRIVE 12 [get_ports vout_de]
set_property DRIVE 12 [get_ports vout_hs]

create_clock -period 6.734 -name vin_clk -waveform {0.000 3.367} [get_ports vin_clk]
