
#########################ethernet###################
create_clock -period 8.000 [get_ports rgmii1_rxc]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii1_rxd[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii1_txd[*]}]
set_property SLEW FAST [get_ports {rgmii1_txd[*]}]

set_property IOSTANDARD LVCMOS33 [get_ports e1_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports e1_mdio]
set_property IOSTANDARD LVCMOS33 [get_ports e1_reset]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii1_rxc]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii1_rxctl]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii1_txc]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii1_txctl]
set_property SLEW FAST [get_ports rgmii1_txc]
set_property SLEW FAST [get_ports rgmii1_txctl]

set_property PACKAGE_PIN C19 [get_ports {rgmii1_rxd[3]}]
set_property PACKAGE_PIN C18 [get_ports {rgmii1_rxd[2]}]
set_property PACKAGE_PIN B18 [get_ports {rgmii1_rxd[1]}]
set_property PACKAGE_PIN A16 [get_ports {rgmii1_rxd[0]}]
set_property PACKAGE_PIN A18 [get_ports {rgmii1_txd[3]}]
set_property PACKAGE_PIN A19 [get_ports {rgmii1_txd[2]}]
set_property PACKAGE_PIN D20 [get_ports {rgmii1_txd[1]}]
set_property PACKAGE_PIN C20 [get_ports {rgmii1_txd[0]}]
set_property PACKAGE_PIN B16 [get_ports e1_mdc]
set_property PACKAGE_PIN B15 [get_ports e1_mdio]
set_property PACKAGE_PIN D16 [get_ports e1_reset]
set_property PACKAGE_PIN B17 [get_ports rgmii1_rxc]
set_property PACKAGE_PIN A15 [get_ports rgmii1_rxctl]
set_property PACKAGE_PIN E18 [get_ports rgmii1_txc]
set_property PACKAGE_PIN F18 [get_ports rgmii1_txctl]

create_clock -period 8.000 [get_ports rgmii2_rxc]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii2_rxd[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii2_txd[*]}]
set_property SLEW FAST [get_ports {rgmii2_txd[*]}]

set_property IOSTANDARD LVCMOS33 [get_ports e2_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports e2_mdio]
set_property IOSTANDARD LVCMOS33 [get_ports e2_reset]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii2_rxc]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii2_rxctl]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii2_txc]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii2_txctl]
set_property SLEW FAST [get_ports rgmii2_txc]
set_property SLEW FAST [get_ports rgmii2_txctl]

set_property PACKAGE_PIN C17 [get_ports {rgmii2_rxd[3]}]
set_property PACKAGE_PIN D19 [get_ports {rgmii2_rxd[2]}]
set_property PACKAGE_PIN B20 [get_ports {rgmii2_rxd[1]}]
set_property PACKAGE_PIN A20 [get_ports {rgmii2_rxd[0]}]
set_property PACKAGE_PIN A13 [get_ports {rgmii2_txd[3]}]
set_property PACKAGE_PIN C15 [get_ports {rgmii2_txd[2]}]
set_property PACKAGE_PIN C14 [get_ports {rgmii2_txd[1]}]
set_property PACKAGE_PIN E17 [get_ports {rgmii2_txd[0]}]
set_property PACKAGE_PIN F20 [get_ports e2_mdc]
set_property PACKAGE_PIN C22 [get_ports e2_mdio]
set_property PACKAGE_PIN B22 [get_ports e2_reset]
set_property PACKAGE_PIN E19 [get_ports rgmii2_rxc]
set_property PACKAGE_PIN F19 [get_ports rgmii2_rxctl]
set_property PACKAGE_PIN A14 [get_ports rgmii2_txc]
set_property PACKAGE_PIN D17 [get_ports rgmii2_txctl]


set_false_path -reset_path -from [get_clocks sys_clk_p] -to [get_clocks rgmii1_rxc]
set_false_path -reset_path -from [get_clocks sys_clk_p] -to [get_clocks rgmii2_rxc]
