# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: I:/ax7103_2019.1/demo/25_video_ethernet/video_ethernet/eth_test.srcs/sources_1/ip/camera_fifo/camera_fifo.xci
# IP: The module: 'camera_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: i:/ax7103_2019.1/demo/25_video_ethernet/video_ethernet/eth_test.srcs/sources_1/ip/camera_fifo/camera_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'camera_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: i:/ax7103_2019.1/demo/25_video_ethernet/video_ethernet/eth_test.srcs/sources_1/ip/camera_fifo/camera_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'camera_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: i:/ax7103_2019.1/demo/25_video_ethernet/video_ethernet/eth_test.srcs/sources_1/ip/camera_fifo/camera_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'camera_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: I:/ax7103_2019.1/demo/25_video_ethernet/video_ethernet/eth_test.srcs/sources_1/ip/camera_fifo/camera_fifo.xci
# IP: The module: 'camera_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: i:/ax7103_2019.1/demo/25_video_ethernet/video_ethernet/eth_test.srcs/sources_1/ip/camera_fifo/camera_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'camera_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: i:/ax7103_2019.1/demo/25_video_ethernet/video_ethernet/eth_test.srcs/sources_1/ip/camera_fifo/camera_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'camera_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: i:/ax7103_2019.1/demo/25_video_ethernet/video_ethernet/eth_test.srcs/sources_1/ip/camera_fifo/camera_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'camera_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
